name: VIRACUT

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Checkout Code
        uses: actions/checkout@v4

      - name: 2. Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 3. Install FFmpeg & Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg fonts-dejavu-core

      - name: 4. Build Video (Utilise le Secret)
        env:
          # Ici, GitHub "invente" le token en allant le chercher dans tes Secrets
          GH_TOKEN: ${{ secrets.VIRACUT_TOKEN }}
        run: python render.py

      - name: 5. Sauvegarde de la Vidéo
        uses: actions/upload-artifact@v4
        with:
          name: video-finale-ia
          path: output.mp4
